### ISSUE TITLE
Help me, Please, to have hlsdl binaries (executables for Windows)!!!

### ISSUE THREAD

**Issue by kokolino2** [canhlinh/hlsdl#1]
Please, could someone tell me where I can find regularly updated binaries (windows executables  versions) (like source files are regularly updated), of this perfect program?

Please, HELP me!!!!!

**Comment by canhlinh** [comment]
@kokolino2 At this moment, this library only supports you integrate it into your code.

I'll build a console application this week. Please wait.

**Comment by canhlinh** [comment]
@kokolino2 For building a console application, You can refer to this https://github.com/canhlinh/hlsdl#how-to-build-a-console-application

**Comment by canhlinh** [comment]
Or this https://github.com/canhlinh/hlsdl/releases/tag/1.0.0

**Comment by kokolino2** [comment]
THANK You, VERY MUCH!!!

Thank you for your efforts and your GREAT responsiveness!!!

You know, I do not know how to make binaries, at all! I am not a programmer!
I tested your binary! It downloads a few segments and stops with the following message: 

"Error: remove ./download/seg157064228.ts: The process cannot access the file bec
ause it is being used by another process."

Strange, what is this another process!? In the URL I used it, there were not encrypted streams/chunks! The result ("Error: No support the m3u8 format"), is similar with one another URL, which is AES-128 encrypted (stream). The URL (of m3u8 stream) is the master one (I mean, the one which has the different m3u8 qualities inside it). When I used the URL of one of those m3u8-streams inside that master m3u8 stream file, the segments were downloaded successfully, but again the same error: 

"Error: remove ./download/seg6734202.ts: The process cannot access the file becau
se it is being used by another process."

I think that your executable, downloads only the current few "ts chuinks" which are in the current m3u8 stream URL address (usually from 3 to 5 ts chinks).

I also noticed that when the m3u8 stream URL has symbols after the m3u8 extension (xxx.m3u8), for example like this one

 "xxxxxx.m3u8?h=d9dafeeda10fd5b5f3c39e022c4=0",

your programme give this error message:

"Error: No support the m3u8 format"

I think that the programme does not continue to the next m3u8 file (which contains the next few ts chinks), i suppose!? I do not know!? I am not sure about it!!!

I did not tested your binary with SAMPLE-AES encrypted streams! Because I do not where to find such one!

I hope I was of any help!!! And I also hope that I was completely clear, for you to may undesrtand what exactly are the problems!!!

Have a nice day!!!!!!!!!!!

And THANK You, again!!!!!!!!

**Comment by canhlinh** [comment]
@kokolino2 FYI, This tool doesn't support download a master list.

**Comment by canhlinh** [comment]
@kokolino2 For this error `Error: remove ./download/seg157064228.ts` I will test on a windows pc to see what is the problems. I will get back to you soon.

**Comment by canhlinh** [comment]
@kokolino2 Actually, I don't have windows PC for testing. But I think I have fixed the bug. Could you please check out the new version at here https://github.com/canhlinh/hlsdl/releases/tag/1.1.0

**Comment by kokolino2** [comment]
Hello again, 'canhlinh'!!!

THANK You for your kindness!!!

I do not know why your programme can not view (different stream qualities, inside one master m3u8 URL address). And your new version (1.1.0), also can not view and download .TS chunks from one of them. May be you have to make your programme first to read the master m3u8 file and to ask for the quality one (the user of your programme), can choose, to download!
And after that, to go to the URL of that quality and then to get TS chunks from the same that m3u8 quality!

Below is the result (with the problem), with the new version (1.1.0), which is the same as with the previous your version. I copied it from my "Command Prompt" window (on my WindowsXP, x64, SP2). I must also try 'hlsdl' (both your versions) on my Windows 7, SP1, x64 PC (which I have not make it, yet):

[[[

K:\My_DocsK\My_VideosK\OnlineTVK>hlsdl -u "http://e201-nlds107.cdn.bg/nlds/nov
aplay2/novaent/as/live/novaent_hd_1600_pc.m3u8?h=d9dafeeda10fd5b5f3c39e022c4635a
7.1558255294161&hdnea=exp=1558255354~acl=/*~hmac=F70DD7344F91E3CB6D5A41809662097
2A35A382011ADE96C3B2069898135D8C5&nltid=novaplay&nltdt=0"
2019/10/12 14:46:06 Downloading segment 6773735
2019/10/12 14:46:06 Downloading segment 6773736
2019/10/12 14:46:08 Downloaded segment 6773735
2019/10/12 14:46:08 Downloading segment 6773737
2019/10/12 14:46:09 Downloaded segment 6773736
2019/10/12 14:46:09 Downloading segment 6773738
2019/10/12 14:46:10 Downloaded segment 6773737
2019/10/12 14:46:10 Downloading segment 6773739
2019/10/12 14:46:11 Downloaded segment 6773738
2019/10/12 14:46:11 Downloading segment 6773740
2019/10/12 14:46:11 Downloaded segment 6773739
2019/10/12 14:46:11 Downloading segment 6773741
2019/10/12 14:46:13 Downloaded segment 6773740
2019/10/12 14:46:13 Downloading segment 6773742
2019/10/12 14:46:13 Downloaded segment 6773741
2019/10/12 14:46:13 Downloading segment 6773743
2019/10/12 14:46:14 Downloaded segment 6773742
2019/10/12 14:46:14 Downloading segment 6773744
2019/10/12 14:46:15 Downloaded segment 6773743
2019/10/12 14:46:16 Downloaded segment 6773744
2019/10/12 14:46:16 Joining segments
2019/10/12 14:46:16 Descrypting 16 0
Error: remove ./download/seg6773735.ts: The process cannot access the file becau
se it is being used by another process.

K:\My_DocsK\My_VideosK\OnlineTVK\

]]]

Master m3u8 URL address (which contains three different qualities, inside itself) is:

"https://e201-nlds107.cdn.bg/nlds/novaplay2/novaent/as/live/novaent_hd_pc.m3u8?h=d9dafeeda10fd5b5f3c39e022c4635a7.1558255294161&hdnea=exp=1558255354~acl=/*~hmac=F70DD7344F91E3CB6D5A418096620972A35A382011ADE96C3B2069898135D8C5&nltid=novaplay&nltdt=0"


Downloaded (.TS) chunks are not deleted/removed, after download finished, like in version 1.0.0!


You know, there is one great programme also called 'hlsdl', just like yours, at this address:

"https://github.com/selsta/hlsdl"

It is also perfect one, but 'selsta' do not want to make windows binaries, because he (or she) uses Linux! This programme (I mean, it's source code), is regularly updated. On his page there is a link to one TXT file, where he (or she) explained how this (making Windows executables) could be done!
You can look at it's source code and it may be helpfull for you!!! I do not know!? It's just an idea (offer) for you!

There were also some binaries (at this URL):

"https://github.com/e2iplayer/hlsdl/releases"

till 'e2iplayer"', closed his (or her) project a few months ago!

His (or her) last version v0.26 was working perfectly. First, when you start it, it offers you, to choose one from all the qualities (inside the master m3u8 stream address), and after then, it starts reading that m3u8 quality defined stream address, and starts download it's .TS chunks! And this hlsdl programme really supports AES-128 encrypted streams (which I tested) (and may be it supports and SAMPLE-AES encrypted, too)!?

I really HOPE that it will be useful to you!!!!!

Good night, 'canhlinh'!!!

**Comment by canhlinh** [comment]
@kokolino2 Yaa,  It seems i have to install a windows pc to test it. I'll get back to you.

**Comment by canhlinh** [comment]
@kokolino2 Finally, I got a windows PC then the bug is fixed. Please try the new version here https://github.com/canhlinh/hlsdl/releases/tag/1.2.0

FYI, I think your suggestion for selecting a m3u8 from a master list is good idea. I'll put it into the new version.

**Comment by kokolino2** [comment]
Hello, 'canhlinh'!!!

THANK You, again for your unflagging efforts!!!

Both versions of your nice programme (1.2.0 and 1.3.0), download only 59 seconds (or it is
may be 60 seconds, if I use a prefessional softawre, which can count seconds and
miliseconds - I do no know) of a live video stream! This coincide with 10 segments (which
your programme downloads), (with a length of 6 seconds, each). Because the live stream from
the site I use (e201-nlds107.cdn.bg), consists of .TS chunks with a length of 6 seconds
each one.

I think that somewhere in your source code, there is a place where you can set a limit of
10 segments only to be downloaded (or may be a limit of 60 seconds - which is not likely
to be).

Of course, the URL of my m3u8 stream is a live video stream.

Created by "hlsdl", version 1.2.0, videos ("video.ts" files), crashed my VLC Player
(version 2.2.1).
Created by your new version (1.3.0), videos, today, DO NOT crash my Vlc Player (v2.2.1)
and they are being played normally.

I also have two ideas for your programme.
The first one is: information about your programme, to be shown (name, version, author,
i.e. You, and so on - all by Your decision), at the beginning, when someone start your
programme.

The second one is: a choice to interrupt downloading (especially for live streams).
For example, by a combination of two buttons/keys (of the keyboard), like "CTRL" + "C"
or something like that.
And it will be good to be a combination of buttons, because one could accidentally press
a key on his keyboard, which will cause interruption of the downloading process.
But all this (I mean INTEERUPTION) is valid only for a video files, not for live streams.
Because in live streams, you have to download one segment, then to decrypt it, and finally
to append it to the previous one in the row of all .TS chunks, of the currently
downloadable live stream video. And finally - to remove/delete it.

My m3u8 URL (which I use to test your programme), is a URL of a live stream, not of a
static video file.

Could you, really make your programme downloading live stream?

THANK You!!!!!!!

Good night, 'canhlinh'!!!

**Comment by canhlinh** [comment]
@kokolino2 Oh, I see.

You want to record a live streaming video.

It is a funny idea. I'll do it at the weekend.

**Comment by kokolino2** [comment]
That's right!!!

THANK You, 'canhlinh'!!!

I saw one mistake in my previous message. I wrote: "But all this (I mean INTEERUPTION) is valid only for a video files, not for live streams."

But I ment :"But all this (I mean INTEERUPTION) is valid only for live streams, not for video files."

Get rest, 'canhlinh' and be HAPPY!!!!!

**Comment by canhlinh** [comment]
@kokolino2 i've added recording option. Please try it at https://github.com/canhlinh/hlsdl/releases/tag/1.4.0

Sample:

```
./bin/hlsdl --url "http://cdn1.live-tv.od.ua:8081/bbb/bbbtv-abr/bbb/bbbtv-720p/chunks.m3u8?nimblesessionid=62115268" --record true
```

**Comment by kokolino2** [comment]
Hello again, 'canhlinh'!!!

Excuse me, for the delay!!!
You know, I tested your new version (1.0.4) on a few sites.

In some cases, the "CTRL+C" keyboard combination, acts with a delay of a few seconds! I do not know whether this is real or just visualisation of the real interruption is delayed!?
I want to ask you,  to make your nice programme, shows the length of the currrent recorded video! You know, when a live video stream goes, in every next m3u8 URL address (containing the next row of TS chunks), there is information of how many seconds is the current TS chunks! (usually from 6 to 10 seconds)! Thus you can make your calculation of the current recorded length of the live video!

[[[

K:\OnlineTVK>hlsdl_w --url "https://e201-nlds107.cdn.bg/nlds
/novaplay2/novaent/as/live/novaent_hd_1600_pc.m3u8?h=d9dafeeda10fd5b5f3c39e022c4
635a7.1558255294161&hdnea=exp=1558255354~acl=/*~hmac=F70DD7344F91E3CB6D5A4180966
20972A35A382011ADE96C3B2069898135D8C5&nltid=novaplay&nltdt=0" --record true
2019/10/31 12:57:27 Start record live streaming movie...
2019/10/31 12:57:30 Recorded segment  7046685
2019/10/31 12:57:32 Recorded segment  7046686
2019/10/31 12:57:34 Recorded segment  7046687
2019/10/31 12:57:36 Recorded segment  7046688
2019/10/31 12:57:39 Recorded segment  7046689
2019/10/31 12:57:40 Recorded segment  7046690
2019/10/31 12:57:43 Recorded segment  7046691
2019/10/31 12:57:45 Recorded segment  7046692
2019/10/31 12:57:47 Recorded segment  7046693
2019/10/31 12:57:48 Got stop signal
2019/10/31 12:57:49 Recorded segment  7046694
2019/10/31 12:57:49 Recorded file at  download\video.ts

K:\OnlineTVK>

]]]

The resulted video (the above one, which is encrypted with AES-128), is normal and plays well!!!



Here is one problem case, I had:

[[[

K:\OnlineTVK\hlsdl_w --url "http://212.39.72.61/PLTV/888888
88/224/3221227427/03.m3u8?rrsip=83.228.88.81&zoneoffset=0&servicetype=1&icpid=&a
ccounttype=1&limitflux=-1&limitdur=-1&tenantId=35901&accountinfo=t%2FKIKfqZnKj97
a3DjVdqGN7MxsY82UhxOk2yuWEgk4oVhbYqnL%2F%2FJDIZYTvTIpyNz8nycYhcv1AuL2y9PIH%2Ft%2
Fw09hBGPpWWMqzMBCXaAmoIZSGRPmXuDJaTJbP%2BEYsGGxX4S6JsK3n3poriTiBkTnSXcFcaAJv8lat
AnfssS0M%3D%3A20190617172536%3AUTC%2C1500493484142937743248921%2C77.76.55.8%2C20
190617172536%2Curn:Huawei:liveTV:iptv917%2C1500493484142937743248921%2C-1%2C0%2C
1%2C%2C%2C2%2C403%2C%2C%2C2%2C492082%2C0%2C486301%2CVYRCcQzssHoolXrlkj7hl0GGNn8%
3D%2C%2C%2C2%2C1%2CEND&GuardEncType=2&it=H4sIAAAAAAAAADWOywrCMBRE_ybL0NzWVBdZKYI
gVbC6ldvkJhbTRpMq-Pe2PrYzc4YzRNS0WSmQOYAAC42EoqR8AcY2pdGyyO0CJbJE9yooYBq9b3tXBTN
hp8PyLDIOQnJRcjFj9fS39uhU9plWj66hqMSfO1B8tpqUSZY_MXF0LpLDoQ0933t8HaP_TRjVPzcxk9k
8K6QcHedsmNIa03Vs2AXTMnQ3jGS2wX0AZdEnYjfUV3RUYUeqf3j_5XbRjDZvWBA1f_UAAAA" --record true
2019/10/31 14:44:29 Start record live streaming movie...
2019/10/31 14:44:32 Recorded segment  262087640
2019/10/31 14:44:35 Recorded segment  262087641
2019/10/31 14:44:38 Recorded segment  262087642
2019/10/31 14:44:45 Recorded segment  262087643
2019/10/31 14:44:48 Recorded segment  262087644
2019/10/31 14:44:55 Got stop signal
2019/10/31 14:44:56 Recorded segment  262087645
2019/10/31 14:44:56 Recorded file at  download\video.ts

K:\OnlineTVK\

]]]

As you can see, 'hlsdl_w.exe' (in my case, I renamed your file to that one), shows that is writing some TS chunks (which are addeded to the main recording video), but when i break the recording, the resulted video file (video.ts) is empty (and with size of 0 bytes).
I do not know why this happens!?
Of course, this live video stream is not encrypted! May be the reason is it's long length!? 

I tested your programme with one another URL (of HLS live streaming video), which is not encrypted and it also is working PERFECT!!!
(Of course, it's URL is not so long, as the above one)!!!

Write down in HELP section of your programme code page, information about the correct way to break the recording!?

And your programme still does not support using master m3u8 (it does not read different formats in one HLS master stream)! It still gives the error massage "Error: No support the m3u8 format".
I mean It still does not  read and after that, offer which quality to select (from the master m3u8 URL address of the recording live stream)!

Have nice day and evening!!!

And THANK You, again!!!!!!!!!!!!!

**Comment by canhlinh** [comment]
@kokolino2 I've released a new version to fix 2 know bugs at here https://github.com/canhlinh/hlsdl/releases/tag/1.4.5

**Comment by kokolino2** [comment]
Happy New Year, canhlinh!!!
I wish You  GOOD LUCK!!!!!

I will write you, soon!

Peter

**Comment by canhlinh** [comment]
@kokolino2 happy new year, Peter.

**Comment by zackmark29** [comment]
Can somebody share new build?
