### ISSUE TITLE
Error: Get data:text/plain;base64,xxxxxxxxxx=: unsupported protocol scheme "data"

### ISSUE THREAD

**Issue by oknchm** [canhlinh/hlsdl#11]
All the segments seemed to download successfully but got an error during merging.

> Downloading... 2m35s  269 / 269  100.00% 2m35s
> Joining segments
> Error: Get data:text/plain;base64,xxxxxxxxxx=: unsupported protocol scheme "data"

The xxxxxxxxxx is a long string of alphanumeric characters. I'm not sure if it contains sensitive information so I redacted it for now.
Hoping someone can help. Thank you!

**Comment by canhlinh** [comment]
Could you give me your download URL ?

**Comment by oknchm** [comment]
> Could you give me your download URL ?

Can I send it to you privately?

**Comment by canhlinh** [comment]
@oknchm After i decoded the key i got this.

```
fpsshy@B[_FF<<WRMHEADER xmlns="http://schemas.microsoft.com/DRM/2007/03/PlayReadyHeader" version="4.0.0.0"><DATA><PROTECTINFO><KEYLEN>16</KEYLEN><ALGID>AESCTR</ALGID></PROTECTINFO><KID>dbJTVZICmSVVBpCTfJgRog==</KID><LA_URL>https://license.eurycrypt.com/eurycrypt/openCARM</LA_URL></DATA></WRMHEADER>
```

It means this mu38 file is created for a specific player.  You can try will `ffplay`. It's not working.

**Comment by canhlinh** [comment]
![Screenshot_20211220_172343](https://user-images.githubusercontent.com/2246996/146752408-60a678e9-0e9f-41d2-8963-8c112f336fd2.png)

**Comment by oknchm** [comment]
@canhlinh That's unfortunate but I understand, thank you.

**Comment by westermeier** [comment]
window.open('data:text/html;charset=utf-8,%3C%21DOCTYPE%20html%3E%0D%0A%3Cht'+
  'ml%20lang%3D%22en%22%3E%0D%0A%3Chead%3E%3Ctitle%3EEmbedded%20Window%3C%2F'+
  'title%3E%3C%2Fhead%3E%0D%0A%3Cbody%3E%3Ch1%3E42%3C%2Fh1%3E%3C%2Fbody%3E%0'+
  'A%3C%2Fhtml%3E%0A%0D%0A','_blank','height=300,width=400');
