### ISSUE TITLE
Windows Build new version

### ISSUE THREAD

**Issue by zackmark29** [canhlinh/hlsdl#4]
Could someone share the newest build version for windows?

**Comment by canhlinh** [comment]
@zackmark29  here you are https://github.com/canhlinh/hlsdl/releases/tag/1.4.6

**Comment by zackmark29** [comment]
> @zackmark29 here you are https://github.com/canhlinh/hlsdl/releases/tag/1.4.6

Thank you so much.

Could you post all the parameters?

**Comment by canhlinh** [comment]
Can you try with `./hlsdl_windows.exe --help`
